### PR TITLE
fix(module:range-picker): clear outline on mouse leave

### LINKED ISSUE #6323: Date range picker: Selection outline remains after mousing away from or dismissing component
https://user-images.githubusercontent.com/28040084/103937347-a24c0500-50f6-11eb-9134-631bbcbc339f.mov

### Reproduction link
[https://stackblitz.com/edit/itzefl--run?file=src/app/app.component.ts](https://stackblitz.com/edit/itzefl--run?file=src/app/app.component.ts)

### Steps to reproduce
Click on the date range picker, hover anywhere over either month calendar, and then move the mouse away from the control entirely. The dotted blue outline around the calendar dates remain visible.

### What is expected?
The dotted blue outline should disappear as soon as the mouse leaves the component.

### What is actually happening?
The dotted blue outline remains visible after mousing away from the component, even after the component is dismissed and then opened again.

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.0.1 |
| Browser | Chrome - latest |

---
This applies to the regular date range picker (i.e., January 1, 2021 - January 7, 2021). 

This is visible in the ng demo page: https://ng.ant.design/components/date-picker/en#nz-range-picker

It behave as expected on the React demo page: https://ant.design/components/date-picker/

### PR DESCRIPTION
**Pull request by keke521jie**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: close #6323

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

File: components/date-picker/inner-popup.component.ts [hunk 1]
```diff
@@ -223,6 +223,12 @@ export class InnerPopupComponent implements OnChanges {
     );
   }
 
+  onLeave(): void {
+    const lastSelectedDate = this.selectedValue.length > 0 ? this.selectedValue[this.selectedValue.length - 1] : void 0;
```
Comment (Laffery) [inline components/date-picker/inner-popup.component.ts]: 直接 `this.selectedValue[this.selectedValue.length - 1]` ?

**Review by Nicoss54 — APPROVED** [review]
LGTM

File: components/date-picker/inner-popup.component.ts (hunk 1 above)
Comment (keke521jie) [reply components/date-picker/inner-popup.component.ts]: Wouldn’t this be more reasonable? No matter which array element we use, there will always be exactly one element in the hover state.
