### PR TITLE
fix(module:tabs): nzLinkRouter not work for the first time

### LINKED ISSUE #9083: nz-tabset's nzLinkRouter not working properly when the app is built for production and it uses lazy-loaded routing modules
### Reproduction link
[https://github.com/ameckl/nz-tabset-error](https://github.com/ameckl/nz-tabset-error)

#### Demo link

https://ng-zorro-antd-tabset-error.pages.dev/?tab=one

### Steps to reproduce
1. Pull the example repository
2. Follow instructions to create production build
3. Run production build

### What is expected?
If the application is accessed with the tab query parameter, like `?tab=one`, the first tab should be loaded.

### What is actually happening?
No tab is loaded, unless I navigate to another one.

| Environment | Info |
|---|---|
| ng-zorro-antd | 19.2.1 |
| Browser | Chrome, Firefox, Safari |

---
When running the app in development mode this issue is not present, only if lazy loaded router modules are used (`loadChildren: () => import('./tabs/tabs.routes').then((m) => m.routes)`) and a production build is made using with outputhashing, optimization enabled.

## This issue is not present in version `19.1.0`.

Image

### PR DESCRIPTION
**Pull request by Laffery**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: close #9083

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

File: components/tabs/tabset.component.ts [hunk 1]
```diff
@@ -483,14 +483,8 @@ export class NzTabSetComponent implements OnInit, AfterContentChecked, OnDestroy
...
-      merge(
-        this.router.events.pipe(
-          filter(e => e instanceof NavigationEnd),
-          delay(0)
-        ),
-        this.tabLinks.changes
-      )
-        .pipe(takeUntil(this.destroy$), startWith(true))
+      merge(this.router.events.pipe(filter(e => e instanceof NavigationEnd)), this.tabLinks.changes)
+        .pipe(delay(0), takeUntil(this.destroy$))
```
Comment (Laffery) [inline components/tabs/tabset.component.ts:487]: `delay(0)` is necessary

File: components/tabs/tabset.component.ts [hunk 2]
```diff
@@ -483,14 +483,8 @@ export class NzTabSetComponent implements OnInit, AfterContentChecked, OnDestroy
...
         throw new Error(`${PREFIX} you should import 'RouterModule' if you want to use 'nzLinkRouter'!`);
       }
-      merge(
-        this.router.events.pipe(
-          filter(e => e instanceof NavigationEnd),
-          delay(0)
-        ),
-        this.tabLinks.changes
-      )
-        .pipe(takeUntil(this.destroy$), startWith(true))
```
Comment (Laffery) [inline components/tabs/tabset.component.ts:493]: `startWith(true)` can be removed due to `this.tabLinks.changes` will emit an event anyway

**Review by HyperLife1119 — APPROVED** [review]
LGTM
