### PR TITLE
fix(module:affix): fix update position when target resize

### LINKED ISSUE #6764: Affix固钉在滚动条消失时，固定状态没有改变
### Reproduction link
[https://codesandbox.io/s/ng-zorro-antd-ivy-forked-hmeb3](https://codesandbox.io/s/ng-zorro-antd-ivy-forked-hmeb3)

### Steps to reproduce
1. 点击remove
2. 弹出modal，点击确认，移除组件
3. 页面已经无法滚动，但affix固定状态没有改变

### What is expected?
修复，affix应该取消固定

### What is actually happening?
Affix固钉在window高度发生改变，滚动条消失时，固定状态没有改变

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.2.0 |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by cipchk**
- close #6764

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

File: components/affix/affix.component.ts [hunk 1]
```diff
@@ -142,15 +144,14 @@ export class NzAffixComponent implements AfterViewInit, OnChanges, OnDestroy, On
...
         ...Object.keys(AffixRespondEvents).map(evName => fromEvent(this.target, evName)),
-        this.offsetChanged$.pipe(
-          takeUntil(this.destroy$),
-          map(() => ({}))
-        )
+        this.offsetChanged$.pipe(map(() => ({}))),
+        this.nzResizeObserver.observe(el)
       )
-        .pipe(auditTime(NZ_AFFIX_DEFAULT_SCROLL_TIME))
+        .pipe(auditTime(NZ_AFFIX_DEFAULT_SCROLL_TIME), takeUntil(this.destroy$))
```
Comment (wendellhu95) [inline components/affix/affix.component.ts:154]: YES!

**Review by wendellhu95 — APPROVED** [review]
LGTM

**Review by wendellhu95 — APPROVED** [review]
All LGTM now.
