### PR TITLE
fix(module:input): fix incorrect control values ​​when using ngModel

### LINKED ISSUE #9740: [nz-input-wrapper] the value of the form control was set incorrectly
### Reproduction link
[https://stackblitz.com/edit/qryukhig?file=src%2Fapp%2Fapp.ts](https://stackblitz.com/edit/qryukhig?file=src%2Fapp%2Fapp.ts)

### Steps to reproduce
1. Initialize a value
2. Binding to elements
3. The initialized value is set to an empty string

### What is expected?
The initialized value is not erroneously modified

### What is actually happening?
Set to an empty string

| Environment | Info |
|---|---|
| ng-zorro-antd | 21.2.0 |
| Browser | chrome |

---
NzInputWrapperComponent组件中获取inputValue时因为生命周期一开始获取到的null,
这个时候formattedValue获取到的值转为了空串然后设置给control,
后续变更检测时inputValue和formattedValue相等又不会重新设置值,
导致一开始设置的空串就变为了实际控件的值

### PR DESCRIPTION
**Pull request by iaosee**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

Fix  #9740 

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

File: components/input/input-wrapper.component.ts [hunk 1]
```diff
@@ -341,7 +341,8 @@ export class NzInputWrapperComponent {
     effect(() => {
       const inputValue = this.inputValue();
       const formattedValue = this.formattedValue();
-      if (formattedValue !== inputValue) {
+
+      if (isNotNil(inputValue) && formattedValue !== inputValue) {
         this.inputDir().ngControl?.control?.setValue(formattedValue);
       }
     });
```
Comment (HyperLife1119) [inline components/input/input-wrapper.component.ts:350]:
```diff
    effect(() => {
++     if (this.nzCount()) {
        const inputValue = this.inputValue();
        const formattedValue = this.formattedValue();

        if (isNotNil(inputValue) && formattedValue !== inputValue) {
          this.inputDir().ngControl?.control?.setValue(formattedValue);
        }
++    }
    });
```

Perhaps adding an nzCount check would be better, WDYT?

Comment (iaosee) [reply components/input/input-wrapper.component.ts:350]: Yes, it's true.
