### PR TITLE
fix(module:description): fix description not accept TemplateRef

### LINKED ISSUE #5127: nz-descriptions-item nzTitle的模板功能无效
### Reproduction link
[https://stackblitz.com/edit/angular-sa2qyz](https://stackblitz.com/edit/angular-sa2qyz)

### Steps to reproduce
<nz-descriptions-item [nzTitle]="tpl">

### What is expected?
nzTitle由指定的模板进行渲染

### What is actually happening?
[object Object]

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.2 |
| Browser | 81.0.4044.122 |

### PR DESCRIPTION
**Pull request by wendellhu95**
close #5127

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by wendellhu95** [comment]
Clearly I didn't implement that in previous versions...

File: components/descriptions/descriptions.component.ts [hunk 1]
```diff
@@ -107,7 +117,9 @@ const defaultColumnMap: { [key in NzBreakpointEnum]: number } = {
                 <tr class="ant-descriptions-row">
                   <ng-container *ngFor="let item of row; let isLast = last">
                     <td class="ant-descriptions-item-label" [colSpan]="item.span">
-                      {{ item.title }}
+                      <ng-container *nzStringTemplateOutlet="item.title">
```
Comment (vthinkxie) [inline components/descriptions/descriptions.component.ts:120]: the type definition of nzTitle also need to update
