### PR TITLE
fix(module:select): shaking when closing dropdown if use a TemplateRef as notFoundContent (#8931)

### LINKED ISSUE #8931: nz-select：When passing in 'nzNotFoundContent' to 'TemplateRef', closing the dropdown menu will cause shaking
### Reproduction link
[https://stackblitz.com/edit/78qr9rss?file=src%2Fapp%2Fapp.component.ts,package.json](https://stackblitz.com/edit/78qr9rss?file=src%2Fapp%2Fapp.component.ts,package.json)

### Steps to reproduce
open the select，then close them。

### What is expected?
nzNotFoundContent passing with TemplateRef, when close the dropdown menu, the animation performance should be consistent.

### What is actually happening?
TemplateRef will be destroyed first, causing the page to go blank before closing

| Environment | Info |
|---|---|
| ng-zorro-antd | 18.2.1 |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by keke521jie**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: close #8931

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

File: components/empty/embed-empty.component.ts [hunk 1]
```diff
@@ -52,6 +53,8 @@ type NzEmptyContentType = 'component' | 'template' | 'string';
     @if (content) {
       @if (contentType === 'string') {
         {{ content }}
+      } @else if (contentType === 'template') {
+        <ng-template [ngTemplateOutlet]="$any(content)" />
       } @else {
```
Comment (Laffery) [inline components/empty/embed-empty.component.ts:58]: string 和 templateRef 都可以用 `nzStringTemplateOutlet`，可以调整下逻辑

```ts
if (contentType === 'portal') {
  <ng-template [cdkPortalOutlet]="contentPortal" />
} else {
  <ng-container *nzStringTemplateOutlet="$any(content)"></ng-container>
}

**Review by Laffery — CHANGES_REQUESTED** [review]

File: components/empty/embed-empty.component.ts [hunk 2]
```diff
@@ -50,8 +51,8 @@ type NzEmptyContentType = 'component' | 'template' | 'string';
   exportAs: 'nzEmbedEmpty',
   template: `
     @if (content) {
-      @if (contentType === 'string') {
-        {{ content }}
+      @if (contentType === 'template' || contentType === 'string') {
+        <ng-container *nzStringTemplateOutlet="$any(content)">{{ content }}</ng-container>
```
Comment (Laffery) [inline components/empty/embed-empty.component.ts]: 补上 context，不需要 $any

```suggestion
        <ng-container *nzStringTemplateOutlet="content; context: { $implicit: this.nzComponentName }">{{ content }}</ng-container>
```

File: components/empty/embed-empty.component.ts [hunk 3]
```diff
@@ -116,9 +117,7 @@ export class NzEmbedEmptyComponent implements OnChanges, OnInit {
     if (typeof content === 'string') {
       this.contentType = 'string';
     } else if (content instanceof TemplateRef) {
-      const context = { $implicit: this.nzComponentName } as NzSafeAny;
       this.contentType = 'template';
-      this.contentPortal = new TemplatePortal(content, this.viewContainerRef, context);
```
Comment (Laffery) [inline components/empty/embed-empty.component.ts:121]: 这里需要清理一下 contentPortal

this.contentPortal = undefined;

**Review by Laffery — CHANGES_REQUESTED** [review]
