### PR TITLE
fix(module:table): fix table fixed style when nzData change

### LINKED ISSUE #4253: table 固定列的样式效果
### Reproduction link
[https://stackblitz.com/edit/angular-cpsrxm?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-cpsrxm?file=src/app/app.component.ts)

### Steps to reproduce
打开 https://stackblitz.com/edit/angular-cpsrxm?file=src/app/app.component.ts 即可

### What is expected?
应该有固定列的阴影效果

### What is actually happening?
没有固定列的阴影效果

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.1 |
| Browser | 谷歌 |

---
如果是静态数据，进去有固定列的阴影效果。  
如果是异步请求的数据，初始没有固定列的阴影效果，需要把滚动条左右移动才会出现。
  
QQ截图20191006163409
QQ截图20191006163425

### PR DESCRIPTION
**Pull request by vthinkxie**
close #4253

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

File: components/table/nz-table.component.ts [hunk 1]
```diff
@@ -269,6 +271,11 @@ export class NzTableComponent<T = any> implements OnInit, AfterViewInit, OnDestr
       this.fitScrollBar();
       this.setScrollPositionClassName();
     }
+    if (changes.nzData) {
+      if (this.platform.isBrowser) {
+        setTimeout(() => this.setScrollPositionClassName());
```
Comment (Svetomechc) [inline components/table/nz-table.component.ts]: This breaks the table for me for some reason:
image

8.3.0:
image
