### PR TITLE
fix(module:progress): fix stroke color is not updated

### LINKED ISSUE #3441: nzStrokeColor does not apply when nz-progress is of type "circle" or "dashboard"
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-3yambk?file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-3yambk?file=src/app/app.component.html)

### Steps to reproduce
Use nzStrokeColor in "nz-progress" with nzType="circle" or "dashboard"

### What is expected?
Stroke color is changed according to nzStrokeColor when progress-bar is circle or dashboard.

### What is actually happening?
Stroke color remains the default color.

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.3.3 |
| Browser | Latest Chrome, Firefox |

### PR DESCRIPTION
**Pull request by wendzhue**
close #3441

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #3441

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

File: components/progress/nz-progress.component.ts [hunk 1]
```diff
@@ -177,6 +177,7 @@ export class NzProgressComponent implements OnInit, OnChanges {
       transition: 'stroke-dashoffset .3s ease 0s, stroke-dasharray .3s ease 0s, stroke .3s'
     };
     this.strokePathStyle = {
+      stroke: this.nzStrokeColor || '',
```
Comment (hsuanxyz) [inline components/progress/nz-progress.component.ts]:
```suggestion
      stroke: this.nzStrokeColor || null,
```
