### PR TITLE
fix(module:date-picker): click date cell not work when changing month or year

### LINKED ISSUE #3499: date-picker: disabled date will be saved
### Reproduction link
[https://ng.ant.design/components/date-picker/zh#components-date-picker-demo-disabled-date](https://ng.ant.design/components/date-picker/zh#components-date-picker-demo-disabled-date)

### Steps to reproduce
- Click first date picker.
- Click one date ('ok' button is disabled now).
- Click outside.

### What is expected?
date can not be saved

### What is actually happening?
date is saved

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.4.1 |
| Browser | all |

---

### PR DESCRIPTION
**Pull request by wenqi73**
Fixes #3499
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by wenqi73** [comment]
Merge after #4833.

File: components/date-picker/date-picker.component.ts [hunk 1]
```diff
@@ -70,6 +70,7 @@ export class NzDatePickerComponent implements OnInit, OnChanges, OnDestroy, Cont
 
   protected destroyed$: Subject<void> = new Subject();
   protected isCustomPlaceHolder: boolean = false;
+  private _showTime: object | boolean;
```
Comment (hsuanxyz) [inline components/date-picker/date-picker.component.ts:73]:
```suggestion
  private showTime: SupportTimeOptions | boolean;
```
