### PR TITLE
fix(module:progress): fix nzFormat not shown status is exception

### LINKED ISSUE #5130: nz-progress nzFormat conflicts with nzStatus(exception)
## What problem does this feature solve?
I need to custom text format and I set [nzFormat] property, but when I set nzStatus property to exception , the nzFormat property lose efficacy.
I think the priority of nzFormat and nzStatus should be the same.
https://stackblitz.com/edit/ng-zorro-antd-start-tdu8u9

## What does the proposed API look like?
I think the priority of nzFormat and nzStatus should be the same. The nzFormat property should always take precedence over nzStatus.

### PR DESCRIPTION
**Pull request by wendellhu95**
close #5130

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by wendellhu95** [comment]
It seems to me that this is adjustment rather than a bug fix.

File: components/progress/progress.component.ts [hunk 1]
```diff
@@ -50,7 +50,7 @@ const defaultFormatter: NzProgressFormatter = (p: number): string => `${p}%`;
   template: `
     <ng-template #progressInfoTemplate>
       <span class="ant-progress-text" *ngIf="nzShowInfo">
-        <ng-container *ngIf="status === 'exception' || (status === 'success' && !nzFormat); else formatTemplate">
+        <ng-container *ngIf="(status === 'exception' || status === 'success') && !nzFormat); else formatTemplate">
```
Comment (vthinkxie) [inline components/progress/progress.component.ts:53]:
```suggestion
        <ng-container *ngIf="((status === 'exception' || status === 'success') && !nzFormat); else formatTemplate">
```
