### PR TITLE
fix(module:table): fix th check not trigger bug

### LINKED ISSUE #3028: custom filter in table check checkbox not trigger change

### LINKED ISSUE #3056: nz-table filter not change after click the checkbox
### Reproduction link
[https://angular-pcjzd1.stackblitz.io](https://angular-pcjzd1.stackblitz.io)

### Steps to reproduce
click the filter button of the column "name", then click the checkbox of filter items, and then click the "Ok" button, the display data of table doesn't change.

### What is expected?
display data of table should be change after click the filter checkbox.

### What is actually happening?
display data doesn't change after do so

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.1 |
| Browser | Chrome 72.0.3626.121 |

### PR DESCRIPTION
**Pull request by vthinkxie**
close #3028 close #3056 close #3058

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

File: components/table/demo/default-filter.ts [hunk 1]
```diff
@@ -58,6 +58,7 @@ export class NzDemoTableDefaultFilterComponent {
   }
 
   filter(listOfSearchName: string[], searchAddress: string): void {
+    console.log(listOfSearchName, searchAddress);
```
Comment (wendzhue) [inline components/table/demo/default-filter.ts]: Got to remove it.

Comment (vthinkxie) [reply components/table/demo/default-filter.ts]: keep it in the demo component, it is ok
