### PR TITLE
test(module:modal): update tests to  zoneless

### LINKED ISSUE #9538: loading dont disappear in modal.confirm when app open provideZonelessChangeDetection()
### Reproduction link
[https://stackblitz.com/edit/mnjzffcv?file=src%2Fapp%2Fapp.config.ts,src%2Fapp%2Fapp.ts](https://stackblitz.com/edit/mnjzffcv?file=src%2Fapp%2Fapp.config.ts,src%2Fapp%2Fapp.ts)

### Steps to reproduce
1.click show modal

2.click ok

### What is expected?
loading will disappear in 1 sec.

### What is actually happening?
loading dont disappear

| Environment | Info |
|---|---|
| ng-zorro-antd | 20.4.1 |
| Browser | chrome 142.0.7444.163 |

### PR DESCRIPTION
**Pull request by Laffery**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: fix #9538

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

File: components/modal/modal-ref.ts [hunk 1]
```diff
@@ -194,11 +194,13 @@ export class NzModalRef<T = NzSafeAny, R = NzSafeAny> implements NzModalLegacyAP
       const result = trigger(this.getContentComponent());
       if (isPromise(result)) {
         this.config[loadingKey] = true;
+        this.updateConfig(this.config);
         let doClose: boolean | void | {} = false;
         try {
           doClose = (await result) as typeof result;
         } finally {
           this.config[loadingKey] = false;
+          this.updateConfig(this.config);
```
Comment (Laffery) [inline components/modal/modal-ref.ts:203]: fix #9538

**Review by Nicoss54 — APPROVED** [review]
LGTM

File: components/modal/modal.spec.ts [hunk 2]
```diff
@@ -130,94 +115,95 @@ describe('modal', () => {
...
     expect(modalRef.getContentComponent() instanceof TestWithModalContentComponent).toBe(true);
     expect(modalRef.getContentComponent().modalRef).toBe(modalRef);
     expect(modalRef.getContentComponentRef()).not.toBeNull();
-    modalRef.close();
   });
 
-  it('should open modal with template', () => {
+  it('should open modal with template', async () => {
     fixture.componentInstance.value = 'Modal';
     fixture.detectChanges();
```
Comment (WwwHhhYran) [inline components/modal/modal.spec.ts]: useless `detectChanges()`

File: components/modal/modal.spec.ts [hunk 3]
```diff
@@ -130,94 +115,95 @@ describe('modal', () => {
...
     expect(fixture.componentInstance.modalRef).toBe(modalRef);
     expect(modalRef.getContentComponentRef()).toBeNull();
     expect(modalRef.getContentComponent()).toBeNull();
-    modalRef.close();
   });
 
-  it('should open modal with template and pass data', () => {
+  it('should open modal with template and pass data', async () => {
     fixture.componentInstance.value = 'Modal';
     fixture.detectChanges();
```
Comment (WwwHhhYran) [inline components/modal/modal.spec.ts]: `useless detectChanges()`

**Review by WwwHhhYran — CHANGES_REQUESTED** [review]

**Review by HyperLife1119 — APPROVED** [review]
LGTM
