### PR TITLE
fix(module:table): fix ExpressionChangedAfterError of nzRight and nzLeft

### LINKED ISSUE #5238: Dynamically pass nzRight to nz-table will report ExpressionChangedAfterItHasBeenCheckedError
### Reproduction link
https://codesandbox.io/s/beautiful-galileo-cml01?file=/src/app/app.component.ts

The 9.x version of the ng-zorro project cannot run on stackblitz, so provide a link to codesandbox

### What is expected?
No error, or provide a solution.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.0 |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by danranVm**
close #5238

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

File: components/table/src/cell/cell-fixed.directive.ts [hunk 1]
```diff
@@ -24,22 +22,18 @@ export class NzCellFixedDirective implements OnChanges {
...
   setIsFirstRight(isRightFirst: boolean): void {
-    this.isFirstRight = isRightFirst;
-    this.cdr.markForCheck();
+    this.renderer.setStyle(this.elementRef.nativeElement, 'ant-table-cell-fix-right-first', isRightFirst);
   }
 
   setIsLastLeft(isLeftLast: boolean): void {
-    this.isLastLeft = isLeftLast;
-    this.cdr.markForCheck();
+    this.renderer.setStyle(this.elementRef.nativeElement, 'ant-table-cell-fix-left-last', isLeftLast);
```
Comment (vthinkxie) [inline components/table/src/cell/cell-fixed.directive.ts:36]: should be addClass and removeClass

Comment (danranVm) [reply components/table/src/cell/cell-fixed.directive.ts]: :cry:  无脑 copy 了。。。

File: components/table/src/cell/cell-fixed.directive.ts [hunk 2]
```diff
@@ -50,11 +36,27 @@ export class NzCellFixedDirective implements OnChanges {
...
-  constructor(private cdr: ChangeDetectorRef, private renderer: Renderer2, private elementRef: ElementRef) {}
+  setIsFirstRight(isRightFirst: boolean): void {
+    this.setFixClass(isRightFirst, 'ant-table-cell-fix-right-first');
+  }
+
+  setIsLastLeft(isLeftLast: boolean): void {
+    this.setFixClass(isLeftLast, 'ant-table-cell-fix-left-last');
+  }
+
+  private setFixClass(flag: boolean, className: string): void {
```
Comment (vthinkxie) [inline components/table/src/cell/cell-fixed.directive.ts:47]: should remove className whenever the flag is true, since the setFixClass function may call many times.
