### PR TITLE
fix(module:cascader): restore its value after cancel search

### LINKED ISSUE #6036: Cascader should restore its value after cancel search
### Reproduction link
[https://stackblitz.com/edit/angular-zz1hq5?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-zz1hq5?file=src/app/app.component.ts)

### Steps to reproduce
1. select something from the cascader
2. type random string into the search bar
3. click outside the menu to close the popover

### What is expected?
1. cascader reverted to original value

### What is actually happening?
1. cascader remains with the search string

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.1.1 |
| Browser | Chrome latest |

---
You can compare with react version https://vulov4--run.stackblitz.io

### PR DESCRIPTION
**Pull request by stygian-desolator**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

close #6036 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

File: components/cascader/cascader.component.ts [hunk 1]
```diff
@@ -429,6 +429,10 @@ export class NzCascaderComponent implements NzCascaderComponentAsSource, OnInit,
       this.cascaderService.syncOptions();
     }
 
+    if (!visible) {
```
Comment (wendellhu95) [inline components/cascader/cascader.component.ts:432]: Use `else`.

**Review by wendellhu95 — COMMENTED** [review]
LGTM. Just a codestyle change requested.
