### PR TITLE
fix(module:progress): should not set success when success percent is …

### LINKED ISSUE #3128: nz-progress incorrectly shows progress complete when nzSuccessPercent < 100
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-iizuvf?file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-iizuvf?file=src/app/app.component.html)

### Steps to reproduce
In nz-progress, use nzSuccessPercent with nzPercent. Set nzPercent to 100, nzSuccessPercent to < 100.

### What is expected?
Progress does not show complete until nzSuccessPercent is set to 100.
Correct behavior shown in react component: https://codesandbox.io/s/67w2r695n

### What is actually happening?
Progress status changes to 'success' when nzPercent changes to 100, ignoring nzSuccessPercent value.

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.3 |
| Browser | Chrome latest/Firefox latest |

### PR DESCRIPTION
**Pull request by wendzhue**
…given

close #3128

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #3128 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

Also refactor this component and add a demo.

### CODE REVIEW

File: components/progress/nz-progress.component.ts [hunk 1]
```diff
@@ -202,40 +150,39 @@ export class NzProgressComponent implements OnInit {
...
-    if (this.nzStatus === 'success') {
+
+    if (this.status === 'success') {
       ret = 'check';
-    }
-    if (this.nzStatus === 'exception') {
+    } else if (this.status === 'exception') {
       ret = 'close';
+    } else {
+      return;
```
Comment (HsuanXyz) [inline components/progress/nz-progress.component.ts]: 这里和之前的行为不一致，检查一下 `return ` 之后的逻辑
