### PR TITLE
fix(module:core): fix global config not working in prod mode

### LINKED ISSUE #4319: 通知提醒框全局配置在生产环境中不生效
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-19p5nt](https://stackblitz.com/edit/ng-zorro-antd-start-19p5nt)

### Steps to reproduce
任何时候必现

### What is expected?
在生产环境里，根据自定义配置正确显示通知提醒框。

### What is actually happening?
全局配置了通知提醒框在右下角显示，在开发环境正常，但在生产环境依然显示在左上角。

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.4.0 |
| Browser | 77.0.3865.120 |

### PR DESCRIPTION
**Pull request by wendzhue**
close #4319

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #4319

## What is the new behavior?

Global configuration works in prod env.

Snipaste_2019-10-20_10-58-43

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

File: components/message/nz-message-container.component.ts [hunk 1]
```diff
@@ -100,16 +100,14 @@ export class NzMessageContainerComponent implements OnInit {
   }
 
   protected subscribeConfigChange(): void {
-    this.nzConfigService
-      .getConfigChangeEventForComponent(trimComponentName(this.constructor.name))
-      .subscribe(() => this.setConfig());
+    this.nzConfigService.getConfigChangeEventForComponent('message').subscribe(() => this.setConfig());
```
Comment (vthinkxie) [inline components/message/nz-message-container.component.ts]: it would better to add an `NZ_CONFIG_COMPONENT_NAME` like other components here

File: components/notification/nz-notification-container.component.ts [hunk 2]
```diff
@@ -64,7 +64,7 @@ export class NzNotificationContainerComponent extends NzMessageContainerComponen
     const newConfig = (this.config = {
       ...this.config,
       ...config,
-      ...this.nzConfigService.getConfigForComponent(trimComponentName(this.constructor.name))
+      ...this.nzConfigService.getConfigForComponent('notification')
```
Comment (vthinkxie) [inline components/notification/nz-notification-container.component.ts]: it would better to add an `NZ_CONFIG_COMPONENT_NAME` like other components here

File: components/spin/nz-spin.component.ts [hunk 3]
```diff
@@ -82,7 +77,7 @@ export class NzSpinComponent implements OnChanges, OnDestroy, OnInit {
     this.subscribeLoading();
 
     this.nzConfigService
-      .getConfigChangeEventForComponent(trimComponentName(this.constructor.name))
+      .getConfigChangeEventForComponent('spin')
```
Comment (vthinkxie) [inline components/spin/nz-spin.component.ts]: NZ_CONFIG_COMPONENT_NAME

File: components/switch/nz-switch.component.ts [hunk 4]
```diff
@@ -60,7 +60,7 @@ export class NzSwitchComponent implements ControlValueAccessor, AfterViewInit, O
   @Input() @InputBoolean() nzControl = false;
   @Input() nzCheckedChildren: string | TemplateRef<void>;
   @Input() nzUnCheckedChildren: string | TemplateRef<void>;
-  @Input() @WithConfig('default') nzSize: NzSizeDSType;
+  @Input() @WithConfig('switch', 'default') nzSize: NzSizeDSType;
```
Comment (vthinkxie) [inline components/switch/nz-switch.component.ts]: it would better to add an NZ_CONFIG_COMPONENT_NAME like other components here

File: components/typography/nz-typography.component.ts [hunk 5]
```diff
@@ -80,7 +80,7 @@ export class NzTypographyComponent implements OnInit, AfterViewInit, OnDestroy,
   @Input() @InputBoolean() nzExpandable = false;
   @Input() @InputBoolean() nzEllipsis = false;
   @Input() nzContent: string;
-  @Input() @WithConfig(1) @InputNumber() nzEllipsisRows: number;
+  @Input() @WithConfig('typography', 1) @InputNumber() nzEllipsisRows: number;
```
Comment (vthinkxie) [inline components/typography/nz-typography.component.ts]: it would better to add an NZ_CONFIG_COMPONENT_NAME like other components here
